// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqfrkxvdrqlgacgzwlyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZnJreHZkcnFsZ2FjZ3p3bHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDYzNzAsImV4cCI6MjA2MzgyMjM3MH0.cUC7ThBniWvt0J88K2NCmYFCag4-hHn_4ch3zIzAfxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);